import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, Building2, Check, HardHat, Map, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import { PublicHeader } from "@/components/public-header";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { featuredItem } from "@/lib/demo-data";
import { MarketCard } from "@/components/market-card";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "BAUSQO – Der passende Auftrag. Das richtige Team." },
    { name: "description", content: "Finde passende Mitarbeiter, Teams, Subunternehmer und Bauaufträge – deutschlandweit." },
    { property: "og:title", content: "BAUSQO – Die Plattform für die Bauwirtschaft" },
    { property: "og:description", content: "Fachkräfte, Teams, Unternehmen und Projekte gezielt zusammenbringen." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}), component: HomePage,
});

const audiences = [
  { icon: HardHat, title: "Für Fachkräfte", text: "Passende Jobs finden, Profil zeigen und direkt auf Projekte bewerben." },
  { icon: Users, title: "Für Teams", text: "Kapazitäten sichtbar machen und als eingespieltes Team neue Einsätze sichern." },
  { icon: Building2, title: "Für Unternehmen", text: "Mitarbeiter, Subunternehmer und Aufträge zentral und effizient finden." },
];

function HomePage() {
  return <div className="min-h-screen bg-background"><PublicHeader />
    <main>
      <section className="blueprint-grid relative overflow-hidden border-b bg-brand-dark text-primary-foreground lg:mx-auto lg:mt-6 lg:max-w-7xl lg:rounded-[2rem] lg:border">
        <div className="absolute inset-y-0 right-0 hidden w-[46%] border-l border-primary-foreground/10 bg-primary/10 lg:block opacity-70" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-14 px-6 py-16 sm:px-10 sm:py-20 lg:grid-cols-[1.08fr_.92fr] lg:px-14 lg:py-24">
          <div><div className="mb-7 inline-flex items-center gap-3 rounded-full border border-primary-foreground/15 bg-primary-foreground/5 px-4 py-2 text-xs font-black uppercase tracking-[0.16em] text-primary-foreground/75"><span className="size-2 rounded-full bg-primary" /> Das Netzwerk für Deutschlands Bauwirtschaft</div>
            <h1 className="max-w-3xl text-balance text-5xl font-black leading-[1.02] tracking-[-0.045em] sm:text-6xl lg:text-7xl">Der passende <span className="text-primary">Auftrag.</span><br />Das richtige <span className="text-primary">Team.</span></h1>
            <p className="mt-7 max-w-2xl text-balance text-lg leading-8 text-primary-foreground/65 sm:text-xl">Finde passende Partner, qualifizierte Fachkräfte und neue Bauprojekte – zentral, transparent und ohne Umwege.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 rounded-xl px-6"><Link to="/registrieren">Jetzt kostenlos starten <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="h-12 rounded-xl border-primary-foreground/25 bg-primary-foreground/5 text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link to="/marketplace">Passenden Auftrag finden</Link></Button></div>
            <div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-primary-foreground/60">{["Kostenlos starten", "Deutschlandweite Suche", "Für alle Gewerke"].map((x) => <span key={x} className="flex items-center gap-2"><Check className="size-4 text-primary" />{x}</span>)}</div>
          </div>
          <div className="relative hidden lg:block"><div className="rounded-[1.6rem] border border-primary-foreground/15 bg-background p-3 text-foreground shadow-2xl"><div className="flex items-center justify-between border-b p-4"><div><p className="text-xs font-bold uppercase text-primary">Aktuelle Empfehlung</p><p className="mt-1 font-extrabold">Ihr BAUSQO</p></div><span className="rounded bg-primary/10 px-2 py-1 text-xs font-bold text-brand-orange">Demo</span></div><div className="p-2"><MarketCard item={featuredItem} /></div></div><div className="absolute -bottom-5 -left-8 flex items-center gap-3 rounded-md bg-primary px-4 py-3 shadow-xl"><Sparkles className="size-5" /><div><p className="text-xs text-primary-foreground/70">Transparenter Score</p><p className="text-sm font-extrabold">94 % Übereinstimmung</p></div></div></div>
        </div>
      </section>

      <section className="border-b bg-background py-20 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-extrabold uppercase text-primary">Eine Plattform. Klare Wege.</p><h2 className="mt-3 text-balance text-3xl font-extrabold sm:text-4xl">Für jeden Einsatz die richtigen Partner.</h2><p className="mt-4 text-muted-foreground">BAUSQO verbindet Angebot und Bedarf entlang der gesamten Projektkette.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{audiences.map(({ icon: Icon, title, text }, i) => <article key={title} className="border-t-4 border-primary bg-card p-7 shadow-sm transition-shadow hover:shadow-lg"><span className="grid size-12 place-items-center rounded-xl bg-primary/10 text-primary"><Icon /></span><p className="mt-7 text-xs font-bold text-muted-foreground">0{i + 1}</p><h3 className="mt-2 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p><Link to="/marketplace" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-primary">Möglichkeiten ansehen <ArrowRight className="size-4" /></Link></article>)}</div></div></section>

      <section className="bg-muted/50 py-20 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-extrabold uppercase text-brand-orange">So funktioniert BAUSQO</p><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">Vom Bedarf zur passenden Besetzung.</h2><div className="mt-8 space-y-6">{[[Search,"Bedarf festlegen","Gewerk, Standort, Zeitraum und Kapazität angeben."],[Sparkles,"Vorschläge vergleichen","Transparente Übereinstimmungen nach relevanten Kriterien sehen."],[Users,"Direkt verbinden","Details prüfen und den nächsten Schritt gemeinsam abstimmen."]].map(([Icon,title,text], i) => { const StepIcon = Icon as typeof Search; return <div key={String(title)} className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-md bg-foreground text-background"><StepIcon className="size-5" /></span><div><p className="text-xs font-bold text-primary">SCHRITT {i+1}</p><h3 className="mt-1 font-extrabold">{String(title)}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{String(text)}</p></div></div>})}</div></div><div className="rounded-2xl bg-brand-dark p-6 text-primary-foreground shadow-xl sm:p-9"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-primary-foreground/50">Beispiel-Match</p><h3 className="mt-2 text-xl font-extrabold">Elektriker · Köln</h3></div><div className="text-right"><p className="text-4xl font-extrabold text-brand-orange">94%</p><p className="text-xs text-primary-foreground/50">Demo-Score</p></div></div><div className="mt-8 space-y-3">{["Fachgebiet passt", "Entfernung 24 km", "Verfügbar zum Projektstart", "Erfahrung passt"].map((x) => <div key={x} className="flex items-center gap-3 border-b border-primary-foreground/10 pb-3 text-sm"><Check className="size-4 text-brand-orange" />{x}</div>)}</div><p className="mt-6 text-xs leading-5 text-primary-foreground/45">Der Score erklärt fachliche und organisatorische Übereinstimmungen. Er ist keine Aussage über Verifizierung oder Vertrauenswürdigkeit.</p></div></div></div></section>

      <section className="border-y bg-background py-20"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 md:grid-cols-3 lg:px-8">{[[ShieldCheck,"Geprüft, nicht behauptet","Ein Verifiziert-Status wird erst nach tatsächlicher Prüfung vergeben."],[BadgeCheck,"Klare Profile","Qualifikationen, Kapazitäten und Verfügbarkeit auf einen Blick."],[Map,"Deutschlandweit suchen","Regionale Ergebnisse mit Standort und Einsatzradius vergleichen."]].map(([Icon,title,text]) => { const C=Icon as typeof ShieldCheck; return <div key={String(title)} className="flex gap-4"><C className="size-7 shrink-0 text-primary"/><div><h3 className="font-extrabold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(text)}</p></div></div>})}</div></section>

      <section className="py-20 sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="text-center"><p className="text-sm font-extrabold uppercase text-primary">Preisübersicht</p><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">Einfach starten. Gezielt wachsen.</h2><p className="mt-4 text-muted-foreground">Tarife sind in Phase 1 nur als Vorschau dargestellt.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[{n:"Free",p:"0 €",f:["Professionelles Profil","Grundlegende Suche","Begrenzte Bewerbungen"]},{n:"Pro",p:"29 €",f:["Erweiterte Suche","Gespeicherte Suchen","Mehr Sichtbarkeit"],hot:true},{n:"Business",p:"79 €",f:["Mehrere Benutzer","Erweitertes Matching","Business-Statistiken"]}].map((plan) => <article key={plan.n} className={`relative rounded-2xl border bg-card p-7 ${plan.hot ? "border-primary shadow-xl" : "shadow-sm"}`}>{plan.hot && <span className="absolute right-4 top-4 rounded bg-primary px-2 py-1 text-xs font-bold text-primary-foreground">Beliebt</span>}<h3 className="text-xl font-extrabold">{plan.n}</h3><p className="mt-5 text-4xl font-extrabold">{plan.p}<span className="text-sm font-medium text-muted-foreground"> / Monat</span></p><div className="my-7 h-px bg-border"/><ul className="space-y-3">{plan.f.map((f)=><li key={f} className="flex gap-2 text-sm"><Check className="size-4 text-primary" />{f}</li>)}</ul><Button className="mt-8 w-full" variant={plan.hot ? "default" : "outline"} disabled>Später verfügbar</Button></article>)}</div></div></section>

      <section className="bg-muted/50 py-20"><div className="mx-auto max-w-3xl px-4 sm:px-6"><h2 className="text-center text-3xl font-extrabold">Häufige Fragen</h2><Accordion type="single" collapsible className="mt-9 border-t">{[["Für wen ist BAUSQO gedacht?","Für Fachkräfte, Selbstständige, Teams, Subunternehmer, Bauunternehmen, Generalunternehmer und Projektleiter in Deutschland."],["Sind die angezeigten Profile echt?","In dieser ersten visuellen Phase sind sämtliche Einträge deutlich gekennzeichnete Demo-Daten."],["Wie entsteht der Match Score?","Später aus Fachgebiet, Entfernung, Verfügbarkeit, Erfahrung, Teamgröße, Budget und weiteren Projektkriterien. Aktuell ist er eine visuelle Vorschau."],["Kann ich BAUSQO bereits buchen?","Nein. Tarife und Zahlungen sind noch nicht aktiviert und werden erst in einer späteren Phase verbunden."]].map(([q,a],i)=><AccordionItem key={q} value={`faq-${i}`}><AccordionTrigger className="text-base">{q}</AccordionTrigger><AccordionContent className="leading-6 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    </main>
    <footer className="bg-brand-dark text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-4 py-12 sm:px-6 md:flex-row md:items-end md:justify-between lg:px-8"><div><p className="text-2xl font-extrabold">BAUSQO</p><p className="mt-2 text-sm text-primary-foreground/55">Die digitale Plattform für die Bauwirtschaft.</p></div><div className="flex flex-wrap gap-6 text-sm text-primary-foreground/55"><Link to="/marketplace">Marketplace</Link><Link to="/login">Anmelden</Link><span>Impressum · vorbereitet</span><span>Datenschutz · vorbereitet</span></div></div></footer>
  </div>;
}