/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BenachrichtigungenRouteImport } from './routes/benachrichtigungen'
import { Route as BewerbungenRouteImport } from './routes/bewerbungen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GespeichertRouteImport } from './routes/gespeichert'
import { Route as KontoTypRouteImport } from './routes/konto-typ'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MeineAuftraegeRouteImport } from './routes/meine-auftraege'
import { Route as NachrichtenRouteImport } from './routes/nachrichten'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AuftragIdRouteImport } from './routes/auftrag.$id'
import { Route as AuftragErstellenRouteImport } from './routes/auftrag.erstellen'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as MarktIdRouteImport } from './routes/markt.$id'
import { Route as ProfilIndexRouteImport } from './routes/profil.index'
import { Route as ProfilBearbeitenRouteImport } from './routes/profil.bearbeiten'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as WorkersIdRouteImport } from './routes/workers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BenachrichtigungenRoute = BenachrichtigungenRouteImport.update({
  id: '/benachrichtigungen',
  path: '/benachrichtigungen',
  getParentRoute: () => rootRouteImport,
} as any)
const BewerbungenRoute = BewerbungenRouteImport.update({
  id: '/bewerbungen',
  path: '/bewerbungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GespeichertRoute = GespeichertRouteImport.update({
  id: '/gespeichert',
  path: '/gespeichert',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoTypRoute = KontoTypRouteImport.update({
  id: '/konto-typ',
  path: '/konto-typ',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MeineAuftraegeRoute = MeineAuftraegeRouteImport.update({
  id: '/meine-auftraege',
  path: '/meine-auftraege',
  getParentRoute: () => rootRouteImport,
} as any)
const NachrichtenRoute = NachrichtenRouteImport.update({
  id: '/nachrichten',
  path: '/nachrichten',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuftragIdRoute = AuftragIdRouteImport.update({
  id: '/auftrag/$id',
  path: '/auftrag/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuftragErstellenRoute = AuftragErstellenRouteImport.update({
  id: '/auftrag/erstellen',
  path: '/auftrag/erstellen',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarktIdRoute = MarktIdRouteImport.update({
  id: '/markt/$id',
  path: '/markt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilBearbeitenRoute = ProfilBearbeitenRouteImport.update({
  id: '/profil/bearbeiten',
  path: '/profil/bearbeiten',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benachrichtigungen': typeof BenachrichtigungenRoute
  '/bewerbungen': typeof BewerbungenRoute
  '/dashboard': typeof DashboardRoute
  '/gespeichert': typeof GespeichertRoute
  '/konto-typ': typeof KontoTypRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/matches': typeof MatchesRoute
  '/meine-auftraege': typeof MeineAuftraegeRoute
  '/nachrichten': typeof NachrichtenRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/auftrag/$id': typeof AuftragIdRoute
  '/auftrag/erstellen': typeof AuftragErstellenRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/markt/$id': typeof MarktIdRoute
  '/profil/bearbeiten': typeof ProfilBearbeitenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/profil/': typeof ProfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benachrichtigungen': typeof BenachrichtigungenRoute
  '/bewerbungen': typeof BewerbungenRoute
  '/dashboard': typeof DashboardRoute
  '/gespeichert': typeof GespeichertRoute
  '/konto-typ': typeof KontoTypRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/matches': typeof MatchesRoute
  '/meine-auftraege': typeof MeineAuftraegeRoute
  '/nachrichten': typeof NachrichtenRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/auftrag/$id': typeof AuftragIdRoute
  '/auftrag/erstellen': typeof AuftragErstellenRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/markt/$id': typeof MarktIdRoute
  '/profil/bearbeiten': typeof ProfilBearbeitenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/profil': typeof ProfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benachrichtigungen': typeof BenachrichtigungenRoute
  '/bewerbungen': typeof BewerbungenRoute
  '/dashboard': typeof DashboardRoute
  '/gespeichert': typeof GespeichertRoute
  '/konto-typ': typeof KontoTypRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/matches': typeof MatchesRoute
  '/meine-auftraege': typeof MeineAuftraegeRoute
  '/nachrichten': typeof NachrichtenRoute
  '/registrieren': typeof RegistrierenRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/auftrag/$id': typeof AuftragIdRoute
  '/auftrag/erstellen': typeof AuftragErstellenRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/markt/$id': typeof MarktIdRoute
  '/profil/bearbeiten': typeof ProfilBearbeitenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/profil/': typeof ProfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/benachrichtigungen'
    | '/bewerbungen'
    | '/dashboard'
    | '/gespeichert'
    | '/konto-typ'
    | '/login'
    | '/marketplace'
    | '/matches'
    | '/meine-auftraege'
    | '/nachrichten'
    | '/registrieren'
    | '/admin/integrations'
    | '/auftrag/$id'
    | '/auftrag/erstellen'
    | '/companies/$id'
    | '/jobs/$id'
    | '/markt/$id'
    | '/profil/bearbeiten'
    | '/projects/$id'
    | '/teams/$id'
    | '/workers/$id'
    | '/profil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/benachrichtigungen'
    | '/bewerbungen'
    | '/dashboard'
    | '/gespeichert'
    | '/konto-typ'
    | '/login'
    | '/marketplace'
    | '/matches'
    | '/meine-auftraege'
    | '/nachrichten'
    | '/registrieren'
    | '/admin/integrations'
    | '/auftrag/$id'
    | '/auftrag/erstellen'
    | '/companies/$id'
    | '/jobs/$id'
    | '/markt/$id'
    | '/profil/bearbeiten'
    | '/projects/$id'
    | '/teams/$id'
    | '/workers/$id'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/benachrichtigungen'
    | '/bewerbungen'
    | '/dashboard'
    | '/gespeichert'
    | '/konto-typ'
    | '/login'
    | '/marketplace'
    | '/matches'
    | '/meine-auftraege'
    | '/nachrichten'
    | '/registrieren'
    | '/admin/integrations'
    | '/auftrag/$id'
    | '/auftrag/erstellen'
    | '/companies/$id'
    | '/jobs/$id'
    | '/markt/$id'
    | '/profil/bearbeiten'
    | '/projects/$id'
    | '/teams/$id'
    | '/workers/$id'
    | '/profil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BenachrichtigungenRoute: typeof BenachrichtigungenRoute
  BewerbungenRoute: typeof BewerbungenRoute
  DashboardRoute: typeof DashboardRoute
  GespeichertRoute: typeof GespeichertRoute
  KontoTypRoute: typeof KontoTypRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MatchesRoute: typeof MatchesRoute
  MeineAuftraegeRoute: typeof MeineAuftraegeRoute
  NachrichtenRoute: typeof NachrichtenRoute
  RegistrierenRoute: typeof RegistrierenRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AuftragIdRoute: typeof AuftragIdRoute
  AuftragErstellenRoute: typeof AuftragErstellenRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  JobsIdRoute: typeof JobsIdRoute
  MarktIdRoute: typeof MarktIdRoute
  ProfilBearbeitenRoute: typeof ProfilBearbeitenRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  TeamsIdRoute: typeof TeamsIdRoute
  WorkersIdRoute: typeof WorkersIdRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benachrichtigungen': {
      id: '/benachrichtigungen'
      path: '/benachrichtigungen'
      fullPath: '/benachrichtigungen'
      preLoaderRoute: typeof BenachrichtigungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewerbungen': {
      id: '/bewerbungen'
      path: '/bewerbungen'
      fullPath: '/bewerbungen'
      preLoaderRoute: typeof BewerbungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gespeichert': {
      id: '/gespeichert'
      path: '/gespeichert'
      fullPath: '/gespeichert'
      preLoaderRoute: typeof GespeichertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto-typ': {
      id: '/konto-typ'
      path: '/konto-typ'
      fullPath: '/konto-typ'
      preLoaderRoute: typeof KontoTypRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meine-auftraege': {
      id: '/meine-auftraege'
      path: '/meine-auftraege'
      fullPath: '/meine-auftraege'
      preLoaderRoute: typeof MeineAuftraegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nachrichten': {
      id: '/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof NachrichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auftrag/$id': {
      id: '/auftrag/$id'
      path: '/auftrag/$id'
      fullPath: '/auftrag/$id'
      preLoaderRoute: typeof AuftragIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auftrag/erstellen': {
      id: '/auftrag/erstellen'
      path: '/auftrag/erstellen'
      fullPath: '/auftrag/erstellen'
      preLoaderRoute: typeof AuftragErstellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markt/$id': {
      id: '/markt/$id'
      path: '/markt/$id'
      fullPath: '/markt/$id'
      preLoaderRoute: typeof MarktIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/bearbeiten': {
      id: '/profil/bearbeiten'
      path: '/profil/bearbeiten'
      fullPath: '/profil/bearbeiten'
      preLoaderRoute: typeof ProfilBearbeitenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BenachrichtigungenRoute: BenachrichtigungenRoute,
  BewerbungenRoute: BewerbungenRoute,
  DashboardRoute: DashboardRoute,
  GespeichertRoute: GespeichertRoute,
  KontoTypRoute: KontoTypRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MatchesRoute: MatchesRoute,
  MeineAuftraegeRoute: MeineAuftraegeRoute,
  NachrichtenRoute: NachrichtenRoute,
  RegistrierenRoute: RegistrierenRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AuftragIdRoute: AuftragIdRoute,
  AuftragErstellenRoute: AuftragErstellenRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  JobsIdRoute: JobsIdRoute,
  MarktIdRoute: MarktIdRoute,
  ProfilBearbeitenRoute: ProfilBearbeitenRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  TeamsIdRoute: TeamsIdRoute,
  WorkersIdRoute: WorkersIdRoute,
  ProfilIndexRoute: ProfilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
