ALTER TABLE public.search_logs
  ADD COLUMN IF NOT EXISTS received INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS accepted INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rejected INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duplicates INTEGER NOT NULL DEFAULT 0;